import re
from typing import Dict, List

from backend.explain_code import LANGUAGE_LABELS, normalize_language


class CodeTranslator:
    def __init__(self, explanation_engine) -> None:
        self.explanation_engine = explanation_engine

    def translate(self, code: str, source_language: str, target_language: str) -> Dict[str, str]:
        source = normalize_language(source_language)
        target = normalize_language(target_language)

        if source == target:
            return {
                "source_language": source,
                "target_language": target,
                "translated_code": code,
                "method": "identity",
                "note": "Source and target languages are the same.",
            }

        prompt = (
            f"Translate this {LANGUAGE_LABELS[source]} code to {LANGUAGE_LABELS[target]}. "
            f"Return only code without explanation.\n{code}\nTranslated code:"
        )
        model_output = self.explanation_engine.generate_text(prompt, max_new_tokens=256, task="translation")
        cleaned = self._clean_translation(model_output)

        if self._looks_valid_translation(cleaned, target):
            return {
                "source_language": source,
                "target_language": target,
                "translated_code": cleaned,
                "method": "huggingface_model",
                "note": "Generated by the pretrained Transformer model.",
            }

        fallback = self._rule_based_translate(code, source, target)
        return {
            "source_language": source,
            "target_language": target,
            "translated_code": fallback,
            "method": "rule_based_fallback",
            "note": "Fallback translation used because the model output was unavailable or low confidence.",
        }

    def _clean_translation(self, text: str) -> str:
        cleaned = (text or "").strip()
        cleaned = re.sub(r"^(translated code:)\s*", "", cleaned, flags=re.IGNORECASE)
        return cleaned.strip()

    def _looks_valid_translation(self, text: str, target_language: str) -> bool:
        if not text or len(text.split()) < 2:
            return False
        if any(token in text.lower() for token in ["summary:", "explanation:", "translated code:"]):
            return False

        heuristics = {
            "python": ["def ", "print(", ":"],
            "java": ["class ", ";", "System.out.println"],
            "c++": ["#include", "cout <<", ";"],
            "c": ["#include", "printf(", ";"],
            "javascript": ["function ", "console.log", ";"],
            "sql": ["select ", "from ", "where "],
        }
        return any(token.lower() in text.lower() for token in heuristics.get(target_language, []))

    def _rule_based_translate(self, code: str, source: str, target: str) -> str:
        if source == "python" and target == "java":
            return self._translate_python_to_java(code)
        if source == "python" and target == "c++":
            return self._translate_python_to_cpp(code)
        if target == "python" and source in {"java", "c++", "c", "javascript"}:
            return self._translate_curly_language_to_python(code, source)
        return (
            f"// Best-effort translation from {source} to {target}\n"
            f"// The pretrained model output was not available, so manual translation rules did not cover this case.\n"
            f"{code}"
        )

    def _translate_python_to_java(self, code: str) -> str:
        function_blocks, main_lines = self._extract_python_functions(code)
        output: List[str] = ["public class TranslatedProgram {"]

        for block in function_blocks:
            output.extend(self._python_function_to_java(block))
            output.append("")

        output.append("    public static void main(String[] args) {")
        output.extend(self._python_statements_to_java(main_lines, base_indent=2))
        output.append("    }")
        output.append("}")
        return "\n".join(self._trim_empty_lines(output))

    def _extract_python_functions(self, code: str) -> tuple[List[List[str]], List[str]]:
        lines = code.splitlines()
        functions: List[List[str]] = []
        main_lines: List[str] = []
        index = 0

        while index < len(lines):
            line = lines[index]
            if re.match(r"^\s*def\s+\w+\(", line) and self._leading_spaces(line) == 0:
                block = [line]
                index += 1
                while index < len(lines):
                    candidate = lines[index]
                    if candidate.strip() == "":
                        block.append(candidate)
                        index += 1
                        continue
                    if self._leading_spaces(candidate) == 0:
                        break
                    block.append(candidate)
                    index += 1
                functions.append(block)
            else:
                main_lines.append(line)
                index += 1
        return functions, main_lines

    def _python_function_to_java(self, lines: List[str]) -> List[str]:
        header = lines[0].strip()
        match = re.match(r"def\s+(\w+)\((.*?)\)\s*:", header)
        name = match.group(1) if match else "translatedFunction"
        args = match.group(2).strip() if match else ""
        java_args = ", ".join(
            f"Object {item.split('=')[0].strip()}"
            for item in args.split(",")
            if item.strip()
        )

        output = [f"    public static Object {name}({java_args}) {{"]
        output.extend(self._python_statements_to_java(lines[1:], base_indent=2))
        output.append("    }")
        return output

    def _translate_python_to_cpp(self, code: str) -> str:
        function_blocks, main_lines = self._extract_python_functions(code)
        output: List[str] = [
            "#include <iostream>",
            "#include <vector>",
            "#include <string>",
            "using namespace std;",
            "",
        ]

        for block in function_blocks:
            output.extend(self._python_function_to_cpp(block))
            output.append("")

        output.append("int main() {")
        output.extend(self._python_statements_to_cpp(main_lines, base_indent=1))
        output.append("    return 0;")
        output.append("}")
        return "\n".join(self._trim_empty_lines(output))

    def _python_function_to_cpp(self, lines: List[str]) -> List[str]:
        header = lines[0].strip()
        match = re.match(r"def\s+(\w+)\((.*?)\)\s*:", header)
        name = match.group(1) if match else "translatedFunction"
        args = match.group(2).strip() if match else ""
        cpp_args = ", ".join(
            f"auto {item.split('=')[0].strip()}"
            for item in args.split(",")
            if item.strip()
        )

        output = [f"auto {name}({cpp_args}) {{"]
        output.extend(self._python_statements_to_cpp(lines[1:], base_indent=1))
        output.append("}")
        return output

    def _python_statements_to_java(self, lines: List[str], base_indent: int) -> List[str]:
        indent_size = self._infer_python_indent(lines)
        current_level = 0
        output: List[str] = []

        for raw_line in lines:
            if not raw_line.strip():
                continue

            stripped = raw_line.strip()
            level = self._leading_spaces(raw_line) // indent_size if indent_size else 0

            while current_level > level:
                output.append(f"{'    ' * (base_indent + current_level - 1)}}}")
                current_level -= 1

            translated = self._python_statement_to_java(stripped)
            output.append(f"{'    ' * (base_indent + level)}{translated}")

            if translated.endswith("{"):
                current_level = level + 1
            else:
                current_level = level

        while current_level > 0:
            output.append(f"{'    ' * (base_indent + current_level - 1)}}}")
            current_level -= 1

        return output

    def _python_statements_to_cpp(self, lines: List[str], base_indent: int) -> List[str]:
        indent_size = self._infer_python_indent(lines)
        current_level = 0
        output: List[str] = []

        for raw_line in lines:
            if not raw_line.strip():
                continue

            stripped = raw_line.strip()
            level = self._leading_spaces(raw_line) // indent_size if indent_size else 0

            while current_level > level:
                output.append(f"{'    ' * (base_indent + current_level - 1)}}}")
                current_level -= 1

            translated = self._python_statement_to_cpp(stripped)
            output.append(f"{'    ' * (base_indent + level)}{translated}")

            if translated.endswith("{"):
                current_level = level + 1
            else:
                current_level = level

        while current_level > 0:
            output.append(f"{'    ' * (base_indent + current_level - 1)}}}")
            current_level -= 1

        return output

    def _python_statement_to_java(self, line: str) -> str:
        if line.startswith("#"):
            return f"// {line[1:].strip()}"

        for_range = re.match(r"for\s+(\w+)\s+in\s+range\(([^,]+),\s*([^)]+)\)\s*:", line)
        if for_range:
            variable, start, stop = for_range.groups()
            return f"for (int {variable} = {start.strip()}; {variable} < {stop.strip()}; {variable}++) {{"

        simple_range = re.match(r"for\s+(\w+)\s+in\s+range\(([^)]+)\)\s*:", line)
        if simple_range:
            variable, stop = simple_range.groups()
            return f"for (int {variable} = 0; {variable} < {stop.strip()}; {variable}++) {{"

        generic_loop = re.match(r"for\s+(\w+)\s+in\s+(.+)\s*:", line)
        if generic_loop:
            variable, iterable = generic_loop.groups()
            return f"for (Object {variable} : {iterable.strip()}) {{"

        if_match = re.match(r"if\s+(.+)\s*:", line)
        if if_match:
            return f"if ({self._java_expression_from_python(if_match.group(1))}) {{"

        elif_match = re.match(r"elif\s+(.+)\s*:", line)
        if elif_match:
            return f"else if ({self._java_expression_from_python(elif_match.group(1))}) {{"

        if line == "else:":
            return "else {"

        while_match = re.match(r"while\s+(.+)\s*:", line)
        if while_match:
            return f"while ({self._java_expression_from_python(while_match.group(1))}) {{"

        print_match = re.match(r"print\((.*)\)", line)
        if print_match:
            return f"System.out.println({print_match.group(1).strip()});"

        return_match = re.match(r"return\s+(.+)", line)
        if return_match:
            return f"return {self._java_expression_from_python(return_match.group(1))};"

        assignment = re.match(r"([A-Za-z_]\w*)\s*=\s*(.+)", line)
        if assignment:
            variable, value = assignment.groups()
            return f"var {variable} = {self._java_expression_from_python(value)};"

        if line == "pass":
            return "// pass"

        if re.match(r"[A-Za-z_]\w*\(.*\)", line):
            return f"{self._java_expression_from_python(line)};"

        return f"// Unsupported Python statement: {line}"

    def _python_statement_to_cpp(self, line: str) -> str:
        if line.startswith("#"):
            return f"// {line[1:].strip()}"

        for_range = re.match(r"for\s+(\w+)\s+in\s+range\(([^,]+),\s*([^)]+)\)\s*:", line)
        if for_range:
            variable, start, stop = for_range.groups()
            return f"for (int {variable} = {start.strip()}; {variable} < {stop.strip()}; ++{variable}) {{"

        simple_range = re.match(r"for\s+(\w+)\s+in\s+range\(([^)]+)\)\s*:", line)
        if simple_range:
            variable, stop = simple_range.groups()
            return f"for (int {variable} = 0; {variable} < {stop.strip()}; ++{variable}) {{"

        generic_loop = re.match(r"for\s+(\w+)\s+in\s+(.+)\s*:", line)
        if generic_loop:
            variable, iterable = generic_loop.groups()
            return f"for (const auto& {variable} : {iterable.strip()}) {{"

        if_match = re.match(r"if\s+(.+)\s*:", line)
        if if_match:
            return f"if ({self._cpp_expression_from_python(if_match.group(1))}) {{"

        elif_match = re.match(r"elif\s+(.+)\s*:", line)
        if elif_match:
            return f"else if ({self._cpp_expression_from_python(elif_match.group(1))}) {{"

        if line == "else:":
            return "else {"

        while_match = re.match(r"while\s+(.+)\s*:", line)
        if while_match:
            return f"while ({self._cpp_expression_from_python(while_match.group(1))}) {{"

        print_match = re.match(r"print\((.*)\)", line)
        if print_match:
            return f"cout << {print_match.group(1).strip()} << endl;"

        return_match = re.match(r"return\s+(.+)", line)
        if return_match:
            return f"return {self._cpp_expression_from_python(return_match.group(1))};"

        assignment = re.match(r"([A-Za-z_]\w*)\s*=\s*(.+)", line)
        if assignment:
            variable, value = assignment.groups()
            return f"auto {variable} = {self._cpp_expression_from_python(value)};"

        if line == "pass":
            return "// pass"

        if re.match(r"[A-Za-z_]\w*\(.*\)", line):
            return f"{self._cpp_expression_from_python(line)};"

        return f"// Unsupported Python statement: {line}"

    def _java_expression_from_python(self, expression: str) -> str:
        converted = expression
        replacements = {
            " and ": " && ",
            " or ": " || ",
            " not ": " !",
            "True": "true",
            "False": "false",
            "None": "null",
        }
        for source, target in replacements.items():
            converted = converted.replace(source, target)
        return converted

    def _cpp_expression_from_python(self, expression: str) -> str:
        converted = expression
        replacements = {
            " and ": " && ",
            " or ": " || ",
            " not ": " !",
            "True": "true",
            "False": "false",
            "None": "nullptr",
        }
        for source, target in replacements.items():
            converted = converted.replace(source, target)
        return converted

    def _translate_curly_language_to_python(self, code: str, source: str) -> str:
        output: List[str] = []
        indent = 0

        for raw_line in code.splitlines():
            line = raw_line.strip()
            if not line:
                continue

            while line.startswith("}"):
                indent = max(indent - 1, 0)
                line = line[1:].strip()

            if not line:
                continue

            open_block = line.endswith("{")
            line = line[:-1].strip() if open_block else line
            translated = self._curly_statement_to_python(line, source)

            if translated is None:
                if open_block:
                    indent += 1
                continue

            output.append(f"{'    ' * indent}{translated}")
            if open_block:
                indent += 1

        return "\n".join(output).strip() or "# Translation could not be generated."

    def _curly_statement_to_python(self, line: str, source: str) -> str | None:
        if line.startswith("#include") or line.startswith("using namespace"):
            return None
        if line.startswith("//"):
            return f"# {line[2:].strip()}"

        class_match = re.match(r"(public\s+)?class\s+(\w+)", line)
        if class_match:
            return f"class {class_match.group(2)}:"

        main_match = re.match(r"(public\s+static\s+void|int)\s+main\s*\((.*?)\)", line)
        if main_match:
            return "def main():"

        method_match = re.match(
            r"(public|private|protected)?\s*(static\s+)?[\w<>\[\]]+\s+(\w+)\s*\((.*?)\)",
            line,
        )
        if method_match and method_match.group(3) != "main":
            name = method_match.group(3)
            raw_args = method_match.group(4)
            arguments = []
            for item in raw_args.split(","):
                item = item.strip()
                if not item:
                    continue
                arguments.append(item.split()[-1].replace("[]", ""))
            return f"def {name}({', '.join(arguments)}):"

        if_match = re.match(r"if\s*\((.+)\)", line)
        if if_match:
            return f"if {self._python_expression_from_curly(if_match.group(1))}:"

        elif_match = re.match(r"else\s+if\s*\((.+)\)", line)
        if elif_match:
            return f"elif {self._python_expression_from_curly(elif_match.group(1))}:"

        if line == "else":
            return "else:"

        while_match = re.match(r"while\s*\((.+)\)", line)
        if while_match:
            return f"while {self._python_expression_from_curly(while_match.group(1))}:"

        loop_match = re.match(
            r"for\s*\(\s*(?:int|long|size_t|var)?\s*(\w+)\s*=\s*([^;]+);\s*\1\s*<\s*([^;]+);\s*\1\+\+\s*\)",
            line,
        )
        if loop_match:
            variable, start, stop = loop_match.groups()
            start = start.strip()
            stop = stop.strip()
            if start == "0":
                return f"for {variable} in range({stop}):"
            return f"for {variable} in range({start}, {stop}):"

        print_match = re.search(r"System\.out\.println\((.*)\)|console\.log\((.*)\)|printf\((.*)\)", line)
        if print_match:
            content = next(group for group in print_match.groups() if group is not None)
            return f"print({content.strip()})"

        if "cout <<" in line:
            content = line.split("cout <<", 1)[1].replace("<< endl", "").replace(";", "").strip()
            return f"print({content})"

        return_match = re.match(r"return\s+(.+);?$", line)
        if return_match:
            return f"return {return_match.group(1).rstrip(';')}"

        assignment_match = re.match(
            r"(?:int|float|double|char|bool|boolean|long|short|String|var|auto)\s+([A-Za-z_]\w*)\s*=\s*(.+);?$",
            line,
        )
        if assignment_match:
            name, value = assignment_match.groups()
            return f"{name} = {value.rstrip(';')}"

        simple_assignment = re.match(r"([A-Za-z_]\w*)\s*=\s*(.+);?$", line)
        if simple_assignment:
            name, value = simple_assignment.groups()
            return f"{name} = {value.rstrip(';')}"

        if line.endswith(";"):
            return line.rstrip(";")

        return line

    def _python_expression_from_curly(self, expression: str) -> str:
        converted = expression
        replacements = {
            "&&": "and",
            "||": "or",
            " true": " True",
            " false": " False",
            " null": " None",
        }
        for source, target in replacements.items():
            converted = converted.replace(source, target)
        converted = converted.replace("!", "not ")
        return converted.strip()

    def _infer_python_indent(self, lines: List[str]) -> int:
        candidates = [self._leading_spaces(line) for line in lines if self._leading_spaces(line) > 0]
        return min(candidates) if candidates else 4

    def _leading_spaces(self, line: str) -> int:
        return len(line) - len(line.lstrip(" "))

    def _trim_empty_lines(self, lines: List[str]) -> List[str]:
        cleaned = []
        previous_blank = False
        for line in lines:
            blank = not line.strip()
            if blank and previous_blank:
                continue
            cleaned.append(line)
            previous_blank = blank
        return cleaned
